import { test, expect } from '@playwright/test';

const BASE_URL = 'http://localhost:5173';

async function login(page, email, password) {
  await page.goto(`${BASE_URL}/auth`);
  // Wait for the specific login form email input
  await page.waitForSelector('#login-email');
  await page.fill('#login-email', email);
  await page.fill('#login-password', password);
  await page.click('form.custom-react-form button[type="submit"]');
  
  // Wait for navigation or specific element that indicates successful login
  await page.waitForSelector('.admin-layout, .ud-profile-card, .btn-logout, .admin-logout-btn', { timeout: 15000 });
}

test.describe('Promo Code Full Flow', () => {
  
  test('Admin Flow: Create, Edit, Delete Promo Codes', async ({ page }) => {
    // 1. Login as Admin
    await login(page, 'admin@baking.com', 'Admin123!');
    
    // 2. Navigate to Loyalty > Promo Codes
    await page.click('a[href="#loyalty"]');
    await page.click('.admin-tab-btn:has-text("Mã giảm giá")');
    
    // Cleanup existing TEST50 if it exists
    const existingRow = page.locator('table.admin-table tbody tr', { hasText: 'TEST50' });
    if (await existingRow.count() > 0) {
      await existingRow.locator('.btn-delete').click();
      await page.click('button:has-text("Xác nhận")');
      await expect(page.locator('text=Đã xóa mã!')).toBeVisible();
    }

    // 3. Create a promo code with custom code (TEST50)
    await page.click('button:has-text("Tạo mã mới")');
    await page.fill('input[placeholder="VD: SALE50K"]', 'TEST50');
    await page.selectOption('select', 'PERCENTAGE');
    await page.fill('input[placeholder="VD: 10"]', '50');
    await page.fill('input[placeholder="Để trống = không giới hạn"]', '100000'); // Max discount
    await page.fill('input[placeholder="0 = không giới hạn"]', '200000'); // Min order
    await page.click('button:has-text("Tạo Mới")');
    
    await expect(page.locator('text=Đã tạo mã!')).toBeVisible();
    await expect(page.locator('code:has-text("TEST50")')).toBeVisible();

    // 4. Create a promo code with empty code (Auto-generated)
    await page.click('button:has-text("Tạo mã mới")');
    await page.selectOption('select', 'FIXED');
    await page.fill('input[placeholder="VD: 50.000"]', '20000');
    await page.click('button:has-text("Tạo Mới")');
    
    await expect(page.locator('text=Đã tạo mã!')).toBeVisible();
    
    // Wait for the table to refresh (the toast might still be there, but we want the table content)
    await page.waitForTimeout(1000); 
    
    const codes = await page.locator('table.admin-table tbody tr td code').allInnerTexts();
    const hasAutoGenerated = codes.some(c => c.length === 8 && c !== 'TEST50');
    expect(hasAutoGenerated).toBe(true);

    // 5. Date validation: End date < Start date
    await page.click('button:has-text("Tạo mã mới")');
    await page.fill('input[name="startDate"]', '2025-12-31');
    await page.fill('input[name="endDate"]', '2025-01-01');
    await expect(page.locator('text=Ngày hết hạn phải sau ngày bắt đầu')).toBeVisible();
    await page.click('button:has-text("Hủy bỏ")');

    // 6. Edit a promo code
    const firstRow = page.locator('table.admin-table tbody tr').first();
    await firstRow.locator('.btn-edit').click();
    // The value input might be different based on type, but we can use the placeholder
    const valueInput = page.locator('input[placeholder="VD: 10"], input[placeholder="VD: 50.000"]');
    await valueInput.fill('30000'); 
    await page.click('button:has-text("Lưu Thay Đổi")');
    await expect(page.locator('text=Đã cập nhật mã!')).toBeVisible();

    // 7. Delete a promo code
    const rowToDelete = page.locator('table.admin-table tbody tr', { hasText: 'TEST50' });
    await rowToDelete.locator('.btn-delete').click();
    await page.click('button:has-text("Xác nhận")');
    await expect(page.locator('text=Đã xóa mã!')).toBeVisible();
    await expect(page.locator('code:has-text("TEST50")')).not.toBeVisible();
  });

  test('Client Flow: Apply Promo Codes at Checkout', async ({ page }) => {
    // Setup: Create test codes via Admin
    await login(page, 'admin@baking.com', 'Admin123!');
    await page.click('a[href="#loyalty"]');
    await page.click('.admin-tab-btn:has-text("Mã giảm giá")');
    
    const codesToCreate = [
      { code: 'PERC10', type: 'PERCENTAGE', value: '10', max: '50000', min: '100000' },
      { code: 'FIX20', type: 'FIXED', value: '20000', max: '', min: '50000' },
      { code: 'MIN500', type: 'FIXED', value: '10000', max: '', min: '500000' }
    ];

    for (const c of codesToCreate) {
      const existing = page.locator('table.admin-table tbody tr', { hasText: c.code });
      if (await existing.count() > 0) {
        await existing.locator('.btn-delete').click();
        await page.click('button:has-text("Xác nhận")');
        await expect(page.locator('text=Đã xóa mã!')).toBeVisible();
      }
      await page.click('button:has-text("Tạo mã mới")');
      await page.fill('input[placeholder="VD: SALE50K"]', c.code);
      await page.selectOption('select', c.type);
      if (c.type === 'PERCENTAGE') {
        await page.fill('input[placeholder="VD: 10"]', c.value);
        await page.fill('input[placeholder="Để trống = không giới hạn"]', c.max);
      } else {
        await page.fill('input[placeholder="VD: 50.000"]', c.value);
      }
      await page.fill('input[placeholder="0 = không giới hạn"]', c.min);
      await page.click('button:has-text("Tạo Mới")');
      await expect(page.locator('text=Đã tạo mã!')).toBeVisible();
    }

    await page.click('.admin-logout-btn');

    // 1. Login as User
    await login(page, 'user@baking.com', 'User123!');

    // 2. Select a course (e.g., 'lam-banh-ngot-pastry' price 450k)
    await page.goto(`${BASE_URL}/program/lam-banh-ngot-pastry`);
    await page.click('.btn-enroll');
    await page.waitForURL(/.*checkout.*/);

    // 3. Apply PERCENTAGE code (PERC10)
    // 450k * 10% = 45k
    await page.fill('input[placeholder="Nhập mã..."]', 'PERC10');
    await page.click('button:has-text("Áp dụng")');
    await expect(page.locator('text=Áp dụng thành công!')).toBeVisible();
    await expect(page.locator('.price-breakdown, .checkout-summary')).toContainText('45.000');

    // 4. Apply FIXED code (FIX20)
    await page.fill('input[placeholder="Nhập mã..."]', 'FIX20');
    await page.click('button:has-text("Áp dụng")');
    await expect(page.locator('text=Áp dụng thành công!')).toBeVisible();
    await expect(page.locator('.price-breakdown, .checkout-summary')).toContainText('20.000');

    // 5. Apply non-existent code
    await page.fill('input[placeholder="Nhập mã..."]', 'NOSUCHCODE');
    await page.click('button:has-text("Áp dụng")');
    await expect(page.locator('text=Mã giảm giá không tồn tại')).toBeVisible();

    // 6. Check minOrderValue constraint (MIN500 on 450k course)
    await page.fill('input[placeholder="Nhập mã..."]', 'MIN500');
    await page.click('button:has-text("Áp dụng")');
    await expect(page.locator('text=Đơn hàng tối thiểu 500.000đ')).toBeVisible();
  });
});
